### ISSUE TITLE
How is progress?

### ISSUE THREAD

**Issue by ronnyhartenstein** [olemartinorg/php-flame-graph#1]
I would love to hear about your progress or ideas on that topic. It is a really good way to visualize performance gaps.

**Comment by olemartinorg** [comment]
Hi! Thanks for stopping by! :-)

I started this repo to do a pretty extensive rewrite of Xdebug-Trace-Visualizer, but I ended up doing some smaller modifications to that project (so that it suited what I wanted it to do). You should have a look at [my fork of that project instead](https://github.com/olemartinorg/Xdebug-Trace-Visualizer).

**Comment by ronnyhartenstein** [comment]
Thank you for reply! 
I don't know about the project but will give it a try. 

BTW: Getting-things-done is sometimes a bitch :)
